apiVersion: batch/v1
kind: Job
metadata:
  name: simplejob
spec:
  template:
    spec:
      containers:
      - name: simple-java-job
        image: deanen1/simple-java-app
        imagePullPolicy: IfNotPresent
        env:
        - name: outcome
          value: complete
        - name: after
          value: "20"
        - name: exitCode
          value: "0"
      restartPolicy: Never
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        operator: In
        values: [2]
    - action: Count
      onExitCodes:
        operator: NotIn
        values: [2]
  backoffLimit: 4
  activeDeadlineSeconds: 10