apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-java-job
            image: deanen1/simple-java-app
            imagePullPolicy: IfNotPresent
            env:
            - name: outcome
              value: complete
            - name: after
              value: "20"
            - name: exitCode
              value: "0"
          restartPolicy: Never
